### ISSUE TITLE
Crash with cgo in concurrent usage

### ISSUE THREAD

**Issue by buixor** [wasilibs/go-re2#38]
Hello,

First, thanks for the cool project, we're [experimenting with it](https://github.com/crowdsecurity/crowdsec/pull/2138) in the context of [crowdsec](https://github.com/crowdsecurity/crowdsec), and the improvements are significant (up to +100%).

However, when switching from WASM to cgo to avoid the mutex and have better concurrency, we found a consistent crash:

```
panic: runtime error: slice bounds out of range [:54043649582105225] with length 163

goroutine 19 [running]:
github.com/wasilibs/go-re2/internal.matchedString(...)
	/home/seb/go/pkg/mod/github.com/wasilibs/go-re2@v0.2.1/internal/re2.go:978
github.com/wasilibs/go-re2/internal.(*Regexp).FindStringSubmatch.func1({0xc000520010?, 0x0?, 0xa3?})
	/home/seb/go/pkg/mod/github.com/wasilibs/go-re2@v0.2.1/internal/re2.go:559 +0x125
github.com/wasilibs/go-re2/internal.readMatches(0xe094d0?, {0x4afd7f?, 0xa3?}, 0xc00069ac80, 0xc1, 0xc0006c6f50)
	/home/seb/go/pkg/mod/github.com/wasilibs/go-re2@v0.2.1/internal/re2_tinygowasm.go:173 +0x54
github.com/wasilibs/go-re2/internal.(*Regexp).findSubmatch(0xc00008e050, {0x0?, 0x0?}, 0x0?)
	/home/seb/go/pkg/mod/github.com/wasilibs/go-re2@v0.2.1/internal/re2.go:593 +0xab
github.com/wasilibs/go-re2/internal.(*Regexp).FindStringSubmatch(0x0?, {0x4afd7f?, 0x0?})
	/home/seb/go/pkg/mod/github.com/wasilibs/go-re2@v0.2.1/internal/re2.go:558 +0x105
main.parse({0x4afd7f, 0xa3}, 0x0?)
	/tmp/cc/main.go:9 +0x37
created by main.main
	/tmp/cc/main.go:21 +0x4a
```

You can reproduce this with the code below:
```golang
package main

import (
	regexp "github.com/wasilibs/go-re2"
)

func parse(logLine string, rx *regexp.Regexp) {
	for {
		rx.FindStringSubmatch(logLine)
	}
}

func main() {
	done := make(chan bool)
	logLine := `139.162.189.33 - - [18/Apr/2018:07:52:34 +0200] "GET /420191f0.css HTTP/1.1" 200 136 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko" "-"`
	rx := `((((((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?)|((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)))|(\b[0-9A-Za-z][0-9A-Za-z-]{0,62}(?:\.[0-9A-Za-z][0-9A-Za-z-]{0,62})*(\.?|\b))) )?(((((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?)|((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)))|(\b[0-9A-Za-z][0-9A-Za-z-]{0,62}(?:\.[0-9A-Za-z][0-9A-Za-z-]{0,62})*(\.?|\b))) - ((([a-zA-Z\.\@\-\+_%]+)))? \[(((?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9])/(\bJan(?:uary|uar)?|Feb(?:ruary|ruar)?|M(?:a|ä)?r(?:ch|z)?|Apr(?:il)?|Ma(?:y|i)?|Jun(?:e|i)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|O(?:c|k)?t(?:ober)?|Nov(?:ember)?|De(?:c|z)(?:ember)?\b)/((?:\d\d){1,2}):((2[0123]|[01]?[0-9]):([0-5][0-9]):((?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?)) ([+-]?(?:[0-9]+)))\] "(\b\w+\b) (.*?) HTTP/(([+-]?(?:(?:[0-9]+(?:\.[0-9]+)?)|(?:\.[0-9]+))))" (([+-]?(?:(?:[0-9]+(?:\.[0-9]+)?)|(?:\.[0-9]+)))) (([+-]?(?:(?:[0-9]+(?:\.[0-9]+)?)|(?:\.[0-9]+)))) "([^"]*)" "([^"]*)"( (([+-]?(?:(?:[0-9]+(?:\.[0-9]+)?)|(?:\.[0-9]+)))) (([+-]?(?:(?:[0-9]+(?:\.[0-9]+)?)|(?:\.[0-9]+)))) \[(.*?)\] \[(.*?)\])?`

	r := regexp.MustCompile(rx)

	for i := 0; i < 20; i++ {
		go parse(logLine, r)
	}

	<-done

}
```
Are we correct in assuming that it is intended that we can safely use the same compiled regexp concurrently? For now we're going to stick to WASM, but really looking forward to be able to use cgo as we have a hard time to get linear gains with wasm (because of the mutex ?).

**Comment by anuraaga** [comment]
Thanks for the repro! Indeed the intention is to be able to use regex without external locking even with cgo. Will take a look.

**Comment by anuraaga** [comment]
Also if you can spare the RAM, with wasm using a sync.pool to compile the same regex multiple times could be an option for improving concurrency with wasm.

**Comment by anuraaga** [comment]
Hi @buixor - I am trying out the repro - on my Mac I have run it for 2min without a crash. Can you confirm how long you run before seeing a crash with your repro? And do you see no crash when not using goroutines, i.e., no concurrency?

Also, I am just using re2 installed from homebrew, it would be good if you can confirm how you are building / installing re2 in your testing.

**Comment by buixor** [comment]
Hello @anuraaga !

 - I ran those tests on linux (kernel 5.x).
 - The crash arrived within seconds (less than 10) with the provided snippet.
 - The crash only seems to happen under concurrency.
 - We were pulling go-re2 directly from your github repository (as we saw there was some new releases, we wanted to try latest version to see if it fixed the bug)

Please let me know if you have trouble to reproduce the bug, happy to help

**Comment by anuraaga** [comment]
Thanks for the details!

> We were pulling go-re2 directly from your github repository (as we saw there was some new releases, we wanted to try latest version to see if it fixed the bug)

Thanks - this is how you are getting go-re2, but as you are using cgo, you also must be providing re2 itself, which is found via `pkg-config`. Can you share how you are installing or building re2, the C++ library? Is it `apt-get` for example?

**Comment by blotus** [comment]
Hello, 

I also manage to reproduce the crash on macos, it is nearly instant (using a freshly installed re2 from brew):
```
~/test/aa ᐅ go build -tags re2_cgo
~/test/aa ᐅ ./re2_repro
panic: runtime error: slice bounds out of range [:90072254402122128] with length 163

goroutine 23 [running]:
github.com/wasilibs/go-re2/internal.matchedString(...)
	/Users/seb/go/pkg/mod/github.com/wasilibs/go-re2@v0.2.1/internal/re2.go:978
github.com/wasilibs/go-re2/internal.(*Regexp).FindStringSubmatch.func1({0x1400001c4a0?, 0x0?, 0xa3?})
	/Users/seb/go/pkg/mod/github.com/wasilibs/go-re2@v0.2.1/internal/re2.go:559 +0x128
github.com/wasilibs/go-re2/internal.readMatches(0x1004cc5a8?, {0x1003e2e7e?, 0xa3?}, 0x140003dd900, 0xc1, 0x140003a2f40)
	/Users/seb/go/pkg/mod/github.com/wasilibs/go-re2@v0.2.1/internal/re2_tinygowasm.go:173 +0x54
github.com/wasilibs/go-re2/internal.(*Regexp).findSubmatch(0x1400007a050, {0x0?, 0x0?}, 0x0?)
	/Users/seb/go/pkg/mod/github.com/wasilibs/go-re2@v0.2.1/internal/re2.go:593 +0xa8
github.com/wasilibs/go-re2/internal.(*Regexp).FindStringSubmatch(0x0?, {0x1003e2e7e?, 0x0?})
	/Users/seb/go/pkg/mod/github.com/wasilibs/go-re2@v0.2.1/internal/re2.go:558 +0xbc
main.parse({0x1003e2e7e, 0xa3}, 0x0?)
	/Users/seb/test/aa/main.go:9 +0x3c
created by main.main
	/Users/seb/test/aa/main.go:21 +0x4c
```

On linux, the test was run on ubuntu 22.04, using re2 from the ubuntu repositories (version 20220201, quite a bit older)

**Comment by anuraaga** [comment]
Thanks for doublechecking @blotus, I could repro. Sorry, had this silly mistake in my test...

https://github.com/wasilibs/go-re2/blob/main/concurrency_test.go#L6

Will take a look into this.

**Comment by anuraaga** [comment]
@blotus Not sure you'll see this reply after so long, but wanted to share that I made a change that should reduce memory usage with the wazero codepath dramatically. If you are interested, it would be cool if you could give the latest unreleased commit a try to see how it goes for you, especially whether performance is enough to not bother with cgo or not. Real world data helps us a lot so if you happen to have some bandwidth to check that it would be really appreciated.

**Comment by anuraaga** [comment]
Hi @buixor - sorry I think I got confused on my previous reply about the original poster of the issue. Not sure you'll see this reply after so long, but just in case see https://github.com/wasilibs/go-re2/issues/38#issuecomment-1867450952
