### ISSUE TITLE
Racey named groups

### ISSUE THREAD

**Issue by Highstead** [wasilibs/go-re2#66]
I get a stack trace when i use named groups and regex in a number of go routines:
```
wasm stack trace:
	.$170(i32) i32
	.$189(i32,i32,i32) i32 [recovered]
	panic: wasm error: out of bounds memory access
wasm stack trace:
	.$170(i32) i32
	.$189(i32,i32,i32) i32

goroutine 262 [running]:
gitlab.com/highstead/hightest/replacer.replace.func1()
	/Users/highstead/highstead/hightest/go/replacer/replacer.go:150 +0x1fc
panic({0x103924c60?, 0x14000461760?})
	/opt/homebrew/opt/go/libexec/src/runtime/panic.go:914 +0x218
github.com/wasilibs/go-re2/internal.namedGroupsIterNext(0x14000e3d400, 0x20ef0)
	/Users/highstead/pkg/mod/github.com/wasilibs/go-re2@v1.4.1-0.20231024042547-5950d6b89a73/internal/re2_wazero.go:288 +0x2d4
github.com/wasilibs/go-re2/internal.subexpNames(0x14000e3d400, 0x2e72884?, 0x1)
	/Users/highstead/pkg/mod/github.com/wasilibs/go-re2@v1.4.1-0.20231024042547-5950d6b89a73/internal/re2.go:864 +0xa4
github.com/wasilibs/go-re2/internal.(*Regexp).SubexpNames(...)
	/Users/highstead/pkg/mod/github.com/wasilibs/go-re2@v1.4.1-0.20231024042547-5950d6b89a73/internal/re2.go:702
github.com/wasilibs/go-re2/internal.(*Regexp).ReplaceAllString(0x1400007e640, {0x14014ec6000, 0x7a5}, {0x1036cb1e3, 0xf})
	/Users/highstead/pkg/mod/github.com/wasilibs/go-re2@v1.4.1-0.20231024042547-5950d6b89a73/internal/re2.go:825 +0x60
```

I can work around this by calling `regex.SubexpNames()` ahead of time, but the prefered method would probably be to put a mutex around:
https://github.com/wasilibs/go-re2/blob/main/internal/re2.go#L702C25-L702C25

Or just initialize the groupnames during the mustcompile function.  

If you're open to either give me a shout and i'll pop a pull request.

**Comment by anuraaga** [comment]
Hi @Highstead - so sorry for the delay on responding. I think an approach of locking around that lazy mutation would make sense, if you're still interested in a PR that would be great, otherwise I'll get to it by end of week. Thanks.

**Comment by Highstead** [comment]
cool, thanks for this.  Sorry i missed this earlier.
