### ISSUE TITLE
v1.5.0 panic: unable to mmap memory: cannot allocate memory

### ISSUE THREAD

**Issue by yhy0** [wasilibs/go-re2#78]
my vps: CPU: 2 cores Memory: 4GiB, This problem will not occur when I fall back to go-re2@v1.4.1、 wazero@v1.7.0
```
panic: unable to mmap memory: cannot allocate memory

goroutine 1 [running]:
github.com/tetratelabs/wazero/internal/wasm.NewMemoryInstance(0xc001190280)
        /root/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.0/internal/wasm/memory.go:85 +0x1d7
github.com/tetratelabs/wazero/internal/wasm.(*ModuleInstance).buildMemory(0xc001070d00, 0xc001102a80)
        /root/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.0/internal/wasm/module.go:658 +0x2d
github.com/tetratelabs/wazero/internal/wasm.(*Store).instantiate(0xc000074b40, {0x500c848, 0x8794120}, 0xc001102a80, {0x3e6ad13, 0x3}, 0xc001178840, {0x8794120, 0x0, 0x0})
        /root/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.0/internal/wasm/store.go:366 +0x2c5
github.com/tetratelabs/wazero/internal/wasm.(*Store).Instantiate(0xc000074b40, {0x500c848, 0x8794120}, 0x0?, {0x3e6ad13?, 0x0?}, 0x0?, {0x8794120, 0x0, 0x0})
        /root/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.0/internal/wasm/store.go:325 +0x5a
github.com/tetratelabs/wazero.(*runtime).InstantiateModule(0xc0011666f0, {0x500c848, 0x8794120}, {0x501d160, 0xc001168580}, {0x5034ec0, 0xc000b73950})
        /root/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.0/runtime.go:312 +0x1e5
github.com/tetratelabs/wazero.(*runtime).InstantiateWithConfig(0xc0011666f0, {0x500c848, 0x8794120}, {0x7d71d70?, 0x553440?, 0xc000e9ff80?}, {0x5034ec0, 0xc000b73950})
        /root/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.0/runtime.go:277 +0x74
github.com/wasilibs/go-re2/internal.init.0()
        /root/go/pkg/mod/github.com/wasilibs/go-re2@v1.5.0/internal/re2_wazero.go:157 +0x34d
```

**Comment by anuraaga** [comment]
Hi @yhy0 - thanks for the report. I realized that the current approach that mmap's a static amount of virtual memory for shared memory doesn't work on smaller machines. I have tried a change to dynamically size it based on total memory available to the process, could you see if it helps?

https://github.com/wasilibs/go-re2/commit/9f8aa894048abebc4f9d0fd48ce77415679ae5da

**Comment by yhy0** [comment]
Everything seems fine now. 👍

**Comment by anuraaga** [comment]
Thanks for confirming! I have issued a patch release with the fix.

**Comment by anuraaga** [comment]
Hi @yhy0 - there have been some tweaks to the memory allocator in the latest `main`. Would you be able to try it to confirm your issue doesn't regress? Unfortunately I don't have good access to a system that reproduced the "cannot allocate memory" issue. Thank you.
