### ISSUE TITLE
panic: runtime error: makeslice: cap out of range

### ISSUE THREAD

**Issue by yhy0** [wasilibs/go-re2#94]
Windows 11

```
panic: runtime error: makeslice: cap out of range

goroutine 1 [running]:
github.com/tetratelabs/wazero/internal/wasm.NewMemoryInstance(0x83cfd40, {0x0, 0x0})
        C:/Users/xxxx/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/wasm/memory.go:87 +0x77
github.com/tetratelabs/wazero/internal/wasm.(*ModuleInstance).buildMemory(0x8471e80, 0x841b108, {0x0, 0x0})
        C:/Users/xxxx/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/wasm/module.go:658 +0x3a
github.com/tetratelabs/wazero/internal/wasm.(*Store).instantiate(0x83e40c0, {0x4dfc730, 0x6de9a20}, 0x841b108, {0x3c5a1fa, 0x3}, 0x83e62a0, {0x6de9a20, 0x0, 0x0})
        C:/Users/xxxx/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/wasm/store.go:369 +0x2fb
github.com/tetratelabs/wazero/internal/wasm.(*Store).Instantiate(0x83e40c0, {0x4dfc730, 0x6de9a20}, 0x841b108, {0x3c5a1fa, 0x3}, 0x83e62a0, {0x6de9a20, 0x0, 0x0})
        C:/Users/xxxx/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/internal/wasm/store.go:326 +0x6b
github.com/tetratelabs/wazero.(*runtime).InstantiateModule(0x809e120, {0x4dfc730, 0x6de9a20}, {0x4e0171c, 0x80ade40}, {0x4e09070, 0x8471e00})
        C:/Users/xxxx/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/runtime.go:312 +0x19e
github.com/tetratelabs/wazero.(*runtime).InstantiateWithConfig(0x809e120, {0x4dfc730, 0x6de9a20}, {0x2fd62f0, 0x1c, 0x1c}, {0x4e09070, 0x8471e00})
        C:/Users/xxxx/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.2/runtime.go:277 +0xa1
github.com/wasilibs/go-re2/internal.init.0()
        C:/Users/xxxx/go/pkg/mod/github.com/wasilibs/go-re2@v1.5.2/internal/re2_wazero.go:170 +0x376
```
go env 

```
set GO111MODULE=
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\xxxx\AppData\Local\go-build
set GOENV=C:\Users\xxxxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=386
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\xxxx\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\xxxx\go
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=C:\Program Files (x86)\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files (x86)\Go\pkg\tool\windows_386
set GOVCS=
set GOVERSION=go1.22.3
set GCCGO=gccgo
set GO386=sse2
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\Github\xxxx\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m32 -mthreads -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\xxxx\AppData\Local\Temp\go-build3867928995=/tmp/go-build -gno-record-gcc-switches
```

**Comment by anuraaga** [comment]
Hi @yhy0 - it looks like it's a 32-bit build on Windows. How much RAM does the system have? I have tried a tweak on main for 32-bit systems, can you see if it helps? 

Note that on 32-bit systems, go-re2 will use interpreter mode so it probably won't be faster than the standard library. It would be good for it to still run though. Note that `GOARCH=amd64` on Windows would run fast and well. Thanks.

**Comment by yhy0** [comment]
Thanks, now it's okay

**Comment by anuraaga** [comment]
Thanks for confirming!
